### ISSUE TITLE
I got multiple traceback errors

### ISSUE THREAD

**Issue by RACM** [mbakholdina/srt-stats-plotting#13]
Hi,

I find the utility very useful, but I got multiple errors when I tried to run it. I use the file in the example directory.
I am using python 3.10 and ran pip3 install requirement.tx as instructed. OS is Ubuntu 22.04, but same result on MACOS.

Traceback (most recent call last):
  File "/home/ubuntu/srt-stats-plotting/plot_srt_stats.py", line 485, in <module>
    plot_graph()
  File "/usr/lib/python3/dist-packages/click/core.py", line 1128, in __call__
    return self.main(*args, **kwargs)
  File "/usr/lib/python3/dist-packages/click/core.py", line 1053, in main
    rv = self.invoke(ctx)
  File "/usr/lib/python3/dist-packages/click/core.py", line 1395, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/lib/python3/dist-packages/click/core.py", line 754, in invoke
    return __callback(*args, **kwargs)
  File "/home/ubuntu/srt-stats-plotting/plot_srt_stats.py", line 375, in plot_graph
    plots['rtt'] = create_rtt_plot(source)
  File "/home/ubuntu/srt-stats-plotting/plot_srt_stats.py", line 139, in create_rtt_plot
    return create_plot(
  File "/home/ubuntu/srt-stats-plotting/plot_srt_stats.py", line 32, in create_plot
    fig = plotting.figure(
  File "/home/ubuntu/.local/lib/python3.10/site-packages/bokeh/plotting/_figure.py", line 190, in __init__
    self._raise_attribute_error_with_matches(name, names | opts.properties())
  File "/home/ubuntu/.local/lib/python3.10/site-packages/bokeh/core/has_props.py", line 368, in _raise_attribute_error_with_matches
    raise AttributeError(f"unexpected attribute {name!r} to {self.__class__.__name__}, {text} attributes are {nice_join(matches)}")
AttributeError: unexpected attribute 'plot_width' to figure, similar attributes are outer_width, width or min_width

**Comment by maxsharabayko** [comment]
> File "/home/ubuntu/srt-stats-plotting/plot_srt_stats.py", line 485, in

Line 485 refers to `pktRcvFilterLoss`. Probably there is no such column in your CSV file. Try to disable it.
